# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - US/EU Development/QA

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to QA Azure Web App - app-salesforce-proxy-centralus-prod-001'
        id: deploy-to-webapp-centralus
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-salesforce-proxy-centralus-prod-001'
          slot-name: 'qa'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CENTRALUS_QA }}
      - name: 'Deploy to Dev Azure Web App - app-salesforce-proxy-westeurope-prod-001'
        id: deploy-to-webapp-westeurope
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-salesforce-proxy-westeurope-prod-001'
          slot-name: 'dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_WESTEUROPE_DEV }}
          package: .
